version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 4672
    ports:
      - 3306:3306
    networks:
      - db-net

networks:
  db-net: {}
