version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: set_password_here!
    ports:
      - 3306:3306
    networks:
      - db-net

networks:
  db-net: {}
